### ISSUE TITLE
Suggest add exposure fusion compare into the toolbox

### ISSUE THREAD

**Issue by hsiaoyi0504** [banterle/HDR_Toolbox#10]
Do you think if it is suitable to add exposure fusion to compare with HDR?
Some works like this Mertens, Tom, Jan Kautz, and Frank Van Reeth. "Exposure fusion." Computer Graphics and Applications, 2007. PG'07. 15th Pacific Conference on. IEEE, 2007.
Provide an alternative choice to produce better LDR from different exposure time image

**Comment by banterle** [comment]
It is not very clear what you wrote, what do you exactly mean?

**Comment by hsiaoyi0504** [comment]
I mean compare to compare to traditional HDR imaging via reconstructed HDR image,
exposure fusion method extend the dynamic range through different method (https://en.wikipedia.org/wiki/Exposure_Fusion) without constructing HDR image first.
Then it's an alternative solution to traditional HDR imaging methods, include such functionality into the toolbox maybe have benefits

**Comment by banterle** [comment]
Such functionality is already in the toolbox. There are three methods implemented at the moment:
1) MertensTMO; the original exposure fusion
2) RamanTMO: the bilateral filter based EF
3) BruceExpoBlendTMO: a different formulation

**Comment by hsiaoyi0504** [comment]
ok thanks,I don't find that, but is it suitable to call that as tonemapping(TMO)?

**Comment by banterle** [comment]
you are welcome.

In my opinion yes, because an exposure fusion operator can still take as input an HDR image, which can be decomposed into an exposures stack, and then to obtain a tone mapped image.

**Comment by hsiaoyi0504** [comment]
OK, thanks.
But one another question I want to ask is that you have implemented your own Mertens' method or just use the source code? I have taken a look at the code, but it seems like that you have implemented by yourself. And I know that the exposure fusion of Merten's method have source code implemented by the author of the paper,that is, Merten.

**Comment by banterle** [comment]
you are welcome. It is mine implementation.

**Comment by hsiaoyi0504** [comment]
Ok ,thanks,
then can I include original implementation into the toolbox?maybe another demo can be created

**Comment by banterle** [comment]
you are welcome. Unfortunately, you can not; when this toolbox was conceived for the book the main point was to have uniform code written from scratch.

**Comment by hsiaoyi0504** [comment]
Hmmm.....I think you are right,but think the advantage of the version control(git) and github can achieve both original objective and the completeness/usability  for further research.How about another branch and start to give number to each version?

**Comment by banterle** [comment]
That is very true; but we recently decided to have only two branches; develop (non stable code) and master (release code).

Moreover, it is not always possible, for several reasons, to add whatever code is available on the Internet to an open source project.
