### ISSUE TITLE
A bug in Reinhard tonemapping

### ISSUE THREAD

**Issue by hsiaoyi0504** [banterle/HDR_Toolbox#12]
Hello, I find a bug related Reinhard Tonemapping
in HDR_Toolbox/source_code/Tmo/util/logMean.m

`Lav = exp(mean(img_delta(:)));`
should be
`Lav = mean(exp(img_delta(:)));`

According to the paper

**Comment by hsiaoyi0504** [comment]
Another thing is that in Reinhard's paper
He use `L=0.27R+0.67G+0.06B` for luminance, which is different from the implementation in the `lum` function

**Comment by banterle** [comment]
thank you very much for your reports.

However, the paper has a typo on that equation, so what you find in the toolbox is  correct.

Regarding, the second bit, I use CIE XYZ standard luminance from linear RGB to XYZ;
which is very similar to what you propose. The differences will tinily impact to the final
results of the algorithm.

**Comment by hsiaoyi0504** [comment]
Ok, thanks.
I didn't find that is type, sorry

**Comment by hsiaoyi0504** [comment]
But maybe use original implementation would be more useful to have further research value, when make some comparison with other method?

**Comment by banterle** [comment]
I think that the differences between using CIE XYZ luminance and the other one are so tiny which does not make sense; I may have a thought on this but I cannot promise anything.

**Comment by banterle** [comment]
This issue is closed
