### ISSUE TITLE
ColorCorrectionSigmoid missing

### ISSUE THREAD

**Issue by Garoe** [banterle/HDR_Toolbox#13]
The tone mapping PattanaikVisualAdaptationStaticTMO uses the function ColorCorrectionSigmoid however that function is missing in the ColorCorrection folder.

**Comment by banterle** [comment]
thanks for this, I think that I fixed this issue. Please have a try to it.

Note that this operator requires real-world luminance values, otherwise it will generate extremely dark images.

**Comment by Garoe** [comment]
That worked, thanks for the quick fix.

**Comment by banterle** [comment]
you are welcome!
