### ISSUE TITLE
Typo in `KrawczykTMO.m'

### ISSUE THREAD

**Issue by 0x414c** [banterle/HDR_Toolbox#23]
There is a typo at [line 52 of `KrawczykTMO.m`](https://github.com/banterle/HDR_Toolbox/blob/master/source_code/Tmo/KrawczykTMO.m#L52) (`epislon` -> `epsilon`)
But `epsilon' is not in the scope. Which value should it have?

**Comment by banterle** [comment]
This typo/error is not present in the devel branch. Please, raise issues on the devel branch and not on the master branch as written on the main web page of the project.
