### ISSUE TITLE
pfm file

### ISSUE THREAD

**Issue by oumaima78** [banterle/HDR_Toolbox#25]
Hello , if I want to calculate the mPSNR between two pfm files then I should load thease images , but it dosen't work 
![sans titre678](https://user-images.githubusercontent.com/29063612/27503272-9f9aab98-5872-11e7-9c70-1cc12def02aa.png)
![sans titre6](https://user-images.githubusercontent.com/29063612/27503237-62d0ff64-5872-11e7-932d-ac0249fa6c72.png)

![sans titre67](https://user-images.githubusercontent.com/29063612/27503282-bd6d3776-5872-11e7-9d2b-5d1a27ea37e2.png)

](url)

**Comment by banterle** [comment]
The screenshots you provided do not make any sense; they are invalid MATLAB code.
