### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ratnajitmukherjee** [banterle/HDR_Toolbox#27]
Dear All, 

Its seems there are the few (very minor) issues with the installHDRTookbox.m file which is mostly based due to the comments made in the file. I will just copy paste the errors for you to kindly fix :) 

>> installHDRToolbox
Error: File: installHDRToolbox.m Line: 86 Column: 44
Unexpected MATLAB expression.
 
>> installHDRToolbox
Error: File: installHDRToolbox.m Line: 86 Column: 44
Unexpected MATLAB expression.
 
>> installHDRToolbox
Error: File: installHDRToolbox.m Line: 86 Column: 44
Unexpected MATLAB expression.
 
>> installHDRToolbox
Error: File: installHDRToolbox.m Line: 91 Column: 1
Unexpected MATLAB operator.
 
>> installHDRToolbox
Error: File: installHDRToolbox.m Line: 98 Column: 1
Unexpected MATLAB operator.
 
>> installHDRToolbox
Error: File: installHDRToolbox.m Line: 106 Column: 1
Unexpected MATLAB operator.
 
Again thanks for your contribution :)

**Comment by banterle** [comment]
fixed. thank you.
