### ISSUE TITLE
How can you make an HDR video using the .exr files?

### ISSUE THREAD

**Issue by ezaAlir** [banterle/HDR_Toolbox#30]
I am trying to make an HDR video using TMOs in the toolbox. The outputs are in exr format. I want to convert these exr frames to HDR video viewable on an HDR capable TV. How is that possible.

Thanks for useful toolbox.

**Comment by banterle** [comment]
> The outputs are in exr format.

What functions are you using?

>  I want to convert these exr frames to HDR video viewable on an HDR capable TV. How is that possible.
You need to convert data into 10/12 bit per color channel RAW files and encode them using H265.

**Comment by ezaAlir** [comment]
> What functions are you using?
> 
hdrimwrite('frame_number.exr');

**Comment by banterle** [comment]
is this full list of commands that you use?

**Comment by banterle** [comment]
> AkyuzTMO, MasiaTMO or other TMOs
These are NOT TMOs are ITMOs/RTMOs or EOs, and they are used to expand the dynamic range of an image and not to compress it. Actually, their names are AkyuzEO, MasiaEO, etc.

> I have tonemapped every frame of a video 
I do not understand this bit, you expand the dynamic range of an image with EOs and then you tone map it, right? This step does not make any sense because you expand the dynamic range and then you compress it again. It's like doing 10^(log10 X) the result of these two operations will be X.

>  I want to turn these frames into a HDR10 video which I can play on an HDR TV.
Probably, you need to encode these EXR files using HEVC. Such functionalities are not in the toolbox at the moment.

>I use multiple commands
It is very difficult to understand what you are doing without the full list because your description is a bit confusing.

**Comment by ezaAlir** [comment]
> These are NOT TMOs are ITMOs/RTMOs or EOs, and they are used to expand the dynamic range of an image and not to compress it. Actually, their names are AkyuzEO, MasiaEO, etc.
 
> I do not understand this bit, you expand the dynamic range of an image with EOs and then you tone map it, right? This step does not make any sense because you expand the dynamic range and then you compress it again. It's like doing 10^(log10 X) the result of these two operations will be X.
> 

Sorry my bad. I meant iTMO not TMO and by tonemapping I meant expand.  I expand the video frames and save them in EXR format.

> > I want to turn these frames into a HDR10 video which I can play on an HDR TV.
> 
> Probably, you need to encode these EXR files using some video codec. Such functionalities are not in the toolbox at the moment. Please try what is suggested here:
> https://developers.google.com/media/vp9/hdr-encoding/

Yes I need to encode these hdr frames. I thought this capability might be built in the toolbox or there might be some more intuitive software because I don't have any experience encoding videos.

**Comment by banterle** [comment]
> Sorry my bad. I meant iTMO not TMO and by tonemapping I meant expand. I expand the video frames and save them in EXR format.

No worries, but everything was very confusing.

>Yes I need to encode these hdr frames. I thought this capability might be built in the toolbox or there might be some more intuitive software because I don't have any experience encoding videos.

It cannot be done using the Toolbox, please check that link. I will close the issue if you have no further questions.

**Comment by ezaAlir** [comment]
No further questions.

Thanks.

**Comment by ShaodongFeng** [comment]
> I am trying to make an HDR video using TMOs in the toolbox. The outputs are in exr format. I want to convert these exr frames to HDR video viewable on an HDR capable TV. How is that possible.
> 
> Thanks for useful toolbox.

Hi, I'm also confused about how to covert the .exr hdr files into hdr10 video?

**Comment by banterle** [comment]
There are no functions to convert .exr videos into HDR10 videos. For that task, you need to use FFMPEG or similar software.
