### ISSUE TITLE
Something wrong in installation 

### ISSUE THREAD

**Issue by Somnus0737** [banterle/HDR_Toolbox#32]
I ran the installHDRToolbox. After few minutes the installation stopped and here are the problems it proposed"read_exr.cpp and write_exr.cpp were not compiled, bilateralFilterS.cpp was not compiled".  What's wrong?

**Comment by smallest** [comment]
I meet the same problem on windows platform.

**Comment by smallest** [comment]
message "read_exr.cpp and write_exr.cpp were not compiled" print in `installHDRToolbox.m`,  as follows：
```
try
    cd([str_cur, '/source_code/IO/']);
    mex('read_exr.cpp');
    mex('write_exr.cpp');
catch err 
    disp('read_exr.cpp and write_exr.cpp were not compiled');
end
```

print the `err` to get the error cause.
```
try
    cd([str_cur, '/source_code/IO/']);
    mex('read_exr.cpp');
    mex('write_exr.cpp');
catch err 
    disp(err)
    disp('read_exr.cpp and write_exr.cpp were not compiled');
end
```

**Comment by banterle** [comment]
Please update to the latest version. Note that you need a c/c++ compiler installed and you need to setup it inside MATLAB running the command: mex -setup. This needs to be done before installation. Please let me know if there are further issues.

**Comment by JakeGWater** [comment]
I ran into the same problem on Windows 10.

I fixed it by:

1. Installed Mingw-w64 compiler from Mathworks Addons
2. Disabled antivirus temporarily

**Comment by banterle** [comment]
Unfortunately, this not an issue of the toolbox, MATLAB MEX requires a C++ compiler installed on the machine. The code for compiling some parts is already inside a try-catch statement to avoid hard crashes.
