### ISSUE TITLE
Do I have the copyright to the python?

### ISSUE THREAD

**Issue by hsqaihkl** [banterle/HDR_Toolbox#33]
Hi,I am a student from china ! I know less in matlab so I want make it to the python.     can I ?

**Comment by vitorsr** [comment]
**Disclaimer: I am not a contributor to this project. Wait for an official answer from one of the maintainers.**

@hsqaihkl this repository is under [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License).

The license of this repository is located at.
https://github.com/banterle/HDR_Toolbox/blob/master/license.txt

My understanding is that you are free to do whatever you want under the following conditions.
* License and copyright notice (you have to preserve the original copyright notice)
* State changes (you have to state what changes you've made)
* Disclose source (you have to reference back to this repository)
* Same license (your code has to be GPL)

**Comment by banterle** [comment]
There is the idea to port it to Python using NumPy.

**Comment by hsqaihkl** [comment]
Is there  the python version?

**Comment by hsqaihkl** [comment]
@vitorsr Yes,I know ! Because I had retrievaled some function in python 
eg:demo_hdr_raw.py .....

**Comment by banterle** [comment]
> Is there the python version?

Not yet.
