### ISSUE TITLE
Different pixel values after imwrite and imread

### ISSUE THREAD

**Issue by Taichi-Pink** [banterle/HDR_Toolbox#34]
![image](https://user-images.githubusercontent.com/30882053/64912330-de31ae80-d6ea-11e9-92be-515cb3adb119.png)

After tone mapping, I wrote an image by imwrite in Matlab.
Then read the image, I found the pixel values are different.

Before write the image, the pixel values of imgOut are decimal in (0,1):
  
![image](https://user-images.githubusercontent.com/30882053/64912362-41234580-d6eb-11e9-9768-f1693ae7f293.png)

After write and read the image, the pixel values of imgg are (0,255):
![image](https://user-images.githubusercontent.com/30882053/64912426-5ba9ee80-d6ec-11e9-829a-4af69a2d50e1.png)

Thanks for the help!!!

**Comment by banterle** [comment]
This is because imwrite converts images from values in [0,1] in double into 8-bit unsigned char in [0,255]. If you want to read back values in [0,1] when you read images you either use ldrimread or cast the image to double and divide by 255:
double(imread('imag.png))/255.0
