### ISSUE TITLE
KrawczyTMO.m

### ISSUE THREAD

**Issue by fehimebetul** [banterle/HDR_Toolbox#36]
Hi Sir, 

In the description of the KrawczyTMO.m , I supposed that the name of the paper is written wrong. I check from your book named "Advanced High Dynamic Range Imagıng"  in the page 82 and Section 3.5.2 you referenced to the paper [204]"Lightness Perception in Tone Reproduction for High Dynamic Range Images". 

However ın the description of the KrawczykTMO.m you cite the paper :

%     The paper describing this technique is:
%     "A Model of Visual Adaptation for Realistic Image Synthesis"
% 	  by Grzegorz Krawczyk, Karol Myszkowski, Hans-Peter Seidel
%     in Proceedings of EUROGRAPHICS 2005

**Comment by banterle** [comment]
Thank you, you are right. I will update the reference.
