### ISSUE TITLE
there is a bug in RandomSpatialSampling implementation

### ISSUE THREAD

**Issue by cancam** [banterle/HDR_Toolbox#44]
First of all, thank you for sharing this comprehensive toolbox. While examining the code I realized a bug in RandomSpatialSampling function. In this: https://github.com/banterle/HDR_Toolbox/blob/75c3ff1fb0ddcb09a0f68ed1f9ed0ad21d3fe389/source_code/Generation/util/RandomSpatialSampling.m#L60 line of RandomSpatialSampling implementation c index is incremented. But I think this variable should be initialized as 1 before the loop. In this buggy version c value is accumulated over the initial value of image width.

**Comment by banterle** [comment]
you are welcome, I will fix this, thank you again for spotting this!
