### ISSUE TITLE
Seems not able to use demo_build_radiance_map to do HDR for the dataset included in the toolbox

### ISSUE THREAD

**Issue by hsiaoyi0504** [banterle/HDR_Toolbox#6]
When I try to use demo_build_radiance_map to generate HDR image for the dataset stack
included in the toolbox, cannot have fine result with it

**Comment by banterle** [comment]
Thanks for pointing this out, I found a few bugs that I will fix them now

**Comment by banterle** [comment]
I made changes adding:
1) Example with aligned stack
2) Improved the two examples using Ward and SIFT alignments. These use a better weight function with partial and misaligned data. The next step will be to add a crop function, because it does not make sense to merge parts without data.
