### ISSUE TITLE
MitsunagaNayarCRF is complete?

### ISSUE THREAD

**Issue by hsiaoyi0504** [banterle/HDR_Toolbox#7]
I have traced the source code of MitsunagaNayarCRF.m
seems the implementation only do 1 iteration
doesn't realize iterative method include in Mitsunaga and Nayar 's paper

**Comment by banterle** [comment]
you are correct, I am working on this part.

**Comment by hsiaoyi0504** [comment]
ok,thanks,I also test this part

**Comment by banterle** [comment]
I made some changes, especially I added more examples for building

**Comment by hsiaoyi0504** [comment]
ok, i suggest you can add the Debevec's dataset
http://www.pauldebevec.com/Research/HDR/SourceImages/Memorial_SourceImages.zip

**Comment by hsiaoyi0504** [comment]
I have tested this dataset
with new version code of demo_build_hdr
but will ouput very strange result....

**Comment by banterle** [comment]
This can not be done, because permissions are required and needed to be granted.
I will add more example soon.

You need to manually add exposure values, there are not in the images' metadata.

**Comment by hsiaoyi0504** [comment]
yes, i have manually add exposure values, but seems something still wrong
but i think its ok, its public available on its own website
http://www.pauldebevec.com/Research/HDR/
maybe only need to cite?

**Comment by banterle** [comment]
No you need explicit permission. I will add another dataset. Please try different weighting functions with that dataset.

**Comment by banterle** [comment]
The issue with dataset is the blue parts in the stack. I guess images were aligned using Homography. The blue parts creates issue in the computation of the CRF. A solution to that is to crop the stack to avoid to include those parts in the estimation of the CRF.

**Comment by hsiaoyi0504** [comment]
I have tried many weight function
but seems all don't work
the image after tonemapping looks like all black
I find the wired warning of rank deficient of 1155,1155,1148 appears
and I really don't know why when i choose nSamples as 900, there will still rank deficient,
it seems not uniform to the inequality Debevec state in his paper.
I have the cropped version, but in the office, maybe i can give it a try tomorrow

**Comment by banterle** [comment]
If you check the CRFs, it is completely wrong for the blue channel.

**Comment by hsiaoyi0504** [comment]
The CRF i get all wrong
looks like this.....
![image](https://cloud.githubusercontent.com/assets/10943928/8727236/3719ebae-2c11-11e5-92ab-79923edd6727.png)

**Comment by banterle** [comment]
ah, you are using the wrong Exposure time value, please try 1/exposure_time as stated in the .txt file

**Comment by hsiaoyi0504** [comment]
Sorry for my stupid mistake....
I will try cropped version in the office
thanks

**Comment by banterle** [comment]
it can happen, you are welcome

**Comment by hsiaoyi0504** [comment]
For more robust, stated in the literature
should correlated the color channel relationship before and after HDR construction(I mean in the generation of the radiance map)

**Comment by banterle** [comment]
More robust methods will be added in the future and they are planned in the road map. However, it takes time to add and test them.

**Comment by hsiaoyi0504** [comment]
Maybe the rank deficient cause from the sampling?

**Comment by hsiaoyi0504** [comment]
![debug](https://cloud.githubusercontent.com/assets/10943928/8738560/a90f6f0c-2c63-11e5-957c-37646e0b0b18.jpg)
even I use the dataset cropped
the result looks like the similar wrong results as the uncropped ones

**Comment by hsiaoyi0504** [comment]
I tried the built-in tonemap function in matlab
test result show that still show error in building the radiance map or construct the CRF

**Comment by banterle** [comment]
I tried to build this dataset with another program, PictureNaut 3.2, but it fails in the middle of the process.

**Comment by hsiaoyi0504** [comment]
Sorry, but i mean use the cropped version, not original one
i have checked another HDR script on github, it works well
Since the CRF reconstructed also used Debevec's method, I think there is a bug in this part
But the tonemapping methods is great, I use that to tonemap the hdr I got through another matlab script on github
I found the cropped version of this on OpenCV extra,
https://github.com/Itseez/opencv_extra/tree/master/testdata/cv/hdr/exposures

**Comment by banterle** [comment]
To be honest with you, I tested that sequence with the cropping and it works.
The CRF is well recovered with cropping. I noticed that that noise can appear if the sequence is built in the linear domain, try to use BuildHDR using 'log' instead of 'linear.

**Comment by hsiaoyi0504** [comment]
Thanks, It works know, but another observation using the same smooth term
suggest that maybe some error occures due to the truncation, i try to find it now
Because when you carefully observe the tonemapped result, still some green noise spread

**Comment by banterle** [comment]
which truncation are you referring to?

**Comment by banterle** [comment]
PS: I will modify from now on the develop branch, so please have a look to it.

**Comment by hsiaoyi0504** [comment]
Sorry, but I am wrong
the bugs may comes from the sampling
I replace the sampling process
then the rank deficient it not occur again
and the output looks like without green spot liked noise 
even if i used a bad sampling methods

**Comment by hsiaoyi0504** [comment]
N=256
I place following code inside the for loop
and replace the gsolve part
    for k=1:N
        for j=1:length(stack_exposure)
            stack_samples(k,j)=stack(k,1,i,j);
        end
    end
    size(stack_samples(:,:))
    g = gsolve(stack_samples(:,:), log_stack_exposure, smoothing_term, W);

**Comment by banterle** [comment]
The Grossberg and Nayar sampling may generate rank deficiency, but the output is more stable with few samples. To get the same with spatial sampling (which was already implemented in the toolbox, and I now renamed as SpatialSampling) does not have the rank deficiency issue but it requires many samples to have stable results (even though it can happen with regular sampling).

When I do the cropping  (for avoiding the blue parts for recovering the CRF), I simply do not get the greenish thingie. I will add the option of the spatial sampling and that is all.

Note that I am doing changes at the moment in the develop branch. Please check that for future.

**Comment by hsiaoyi0504** [comment]
ok,thanks for you explanation
I will check the script again

**Comment by hsiaoyi0504** [comment]
![lambda_20](https://cloud.githubusercontent.com/assets/10943928/8774193/255f2960-2f0e-11e5-8d0a-648595304e24.png)
![untitled](https://cloud.githubusercontent.com/assets/10943928/8774199/2da355b0-2f0e-11e5-8986-050e08302970.jpg)
what i mean a little green noise
But it should not cause rank deficient,
or need to avoid in advance?
More robust method should have lower quality result
Weird, right?

**Comment by banterle** [comment]
Ah ok, I got now what you meant, I analyzed closely the image and I spotted the subtle greenish noise. I will investigate it now.

I will analyze the situation with synthetic data. Thanks again for your devoted help in this.

**Comment by hsiaoyi0504** [comment]
No thank,
It's an awesome project
I'm glad to involve in it

**Comment by banterle** [comment]
you are welcome.
